// Portfolio archive shipped with the site. The admin panel saves overrides to
// slicex_content; the page merges them in at runtime. Layouts are picked per
// item: 'feature' (wide, image + side panel), 'standard' (image over caption)
// and 'split' (copy beside image).

export const PORTFOLIO_CATEGORIES = [
  { key: 'weddings', label: 'Weddings' },
  { key: 'pre-weddings', label: 'Pre-Weddings' },
  { key: 'engagements', label: 'Engagements' },
  { key: 'films', label: 'Films' },
];

export const PORTFOLIO_ITEMS = [
  {
    id: 'gobinda-mamuni',
    layout: 'feature',
    span: '12',
    aspect: '16/9',
    categories: 'weddings films',
    youtubeId: 'jEFML86Tk7g',
    image: 'https://i.ytimg.com/vi/jEFML86Tk7g/maxresdefault.jpg',
    eyebrow: 'FEATURE FILM EXCLUSIVE',
    note: '4K DCI • 2.39:1 ANAMORPHIC',
    tags: ['4K Anamorphic', 'Royal Palace', '3-Day'],
    title: 'Gobinda & Mamuni — Wedding Film',
    desc: 'A full cinematic wedding film blending grand celebration with quiet, intimate family moments. Tap to watch on YouTube.',
    metaLeft: '',
    metaRight: '',
  },
  {
    id: 'vikram-ananya',
    layout: 'standard',
    span: '5',
    aspect: '4/5',
    categories: 'weddings',
    youtubeId: '',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAmIDKGxODGKwZka2xcZentvxUzH3ozk1JKnjhjVy4nB83Fbcpqnd8pUq-2MIK_m1jGXUlo43VwYlY4al_70UbGj_4QwPh_ttYGJcCjXVJLLMsUU9dEsi7POTr-uDWl3NmjRBsZm_TfLa163vhfmMsTrGcpOgE5UMngDjJPgl30UEg2SQ6I2w_wKkzrQkPReC0RyqG9v9gVtgWzIMN2UinNo68PbxMu-mkjyK-Ia3FaEdSYN_uwuZNeyw',
    eyebrow: '',
    note: '',
    tags: ['Chiaroscuro', 'Portra 400'],
    title: 'Vikram & Ananya — Heritage Monochrome',
    desc: 'Deep shadows and delicate lace reflections captured in the quiet prelude before the grand baraat procession at Samode.',
    metaLeft: 'JAIPUR HAVELI PREP & VOWS',
    metaRight: '35MM ANALOG',
  },
  {
    id: 'kabir-tara',
    layout: 'standard',
    span: '7',
    aspect: '16/10',
    categories: 'weddings films',
    youtubeId: '',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOGyW9pc1EubyVnzhDQJetqOukbzc4yMaqizmOeYxR7qGgw7nOoYbCllaRapjSruhivlxG7C_F76ggL0iboys1lOY6H2uGj7unyp2iTBMylZyT2M4PpNhsuoy1GGY7FUU_sTuoPEIHnEx5O5cJnaAST1i3qWMr2JqiKWo-Y5sy_KTjFW46SiANW027UN3nDscsUH1zrvnqd3hyGi6HVKEsnPYsgpFuVDhCH7KfuqNaKcga-MZYh8yM3w',
    eyebrow: '',
    note: "DIRECTOR'S CUT AVAILABLE",
    tags: ['Twilight Vows', 'Jodhpur'],
    title: 'Kabir & Tara — Twilight Vows at Mehrangarh',
    desc: 'An architectural drama set against blue city ramparts. Golden rim lighting highlights raw hand-embellished silk and emotional gazes as night settles over Rajasthan.',
    metaLeft: 'MEHRANGARH RAMPARTS',
    metaRight: 'OCTOBER 2024',
  },
  {
    id: 'dev-myra',
    layout: 'standard',
    span: '6',
    aspect: '16/10',
    categories: 'pre-weddings',
    youtubeId: '',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBne6J962TsrZTi3vS_ZlQJvesYvuNgtb1oXm-B0gHuqh91ErRBXLvsLza8RuQCtiG_Sq7MVgZqzOuXmcTDJt__QNQQDOR93G4N1_27iWfsn4x6rQxWp1y8HuFNo9NNfcvcP5z6NqQlY7IfzNf484ruxVNVPvyEbVvitPhoL10waz40j6pcVrh0jD5pI1Twoya1gFUQ02Od5rJ3XiNRQQhBudN2-pkPE54SjOfAhGjaKnZJreJGEsLzkg',
    eyebrow: '',
    note: '',
    tags: ['Kodak Portra', 'Raw Candid'],
    title: 'Dev & Myra — Haldi Sunlight & Festivities',
    desc: 'Unfiltered joy in motion. Splashes of saffron water, yellow silk dupattas, and natural laughter caught on high-speed medium format analog lenses.',
    metaLeft: 'MARIGOLD COURTYARD • JAIPUR',
    metaRight: 'DAY 01',
  },
  {
    id: 'samarth-tanvi',
    layout: 'standard',
    span: '6',
    aspect: '16/10',
    categories: 'weddings',
    youtubeId: '',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfxA6nU3FE1OzPKUCY63_Gy4opS7nUrvt10bcwF4TpVULb7RXBs4Ye4UwVaptCUIfve6LTLbBcasqf6PaiHRm6O9Xzd-5WfUg-KwnKB97flgXchSSaa8xP0b7lCF_URgX_5XoQWzHkEuhMTpTzUlAIF9IzGSMmBOjXycYyyWLMDq2WAzs-EXwfCkW4OU7EcnZJFp0qrgO3wxOgq3V4aMNPLDi9h4gF1eW6PFI4gBOxx4ifOnfNJQepVQ',
    eyebrow: '',
    note: '',
    tags: ['Emotional Documentary', '35mm Film Still'],
    title: 'Samarth & Tanvi — The Varmala Embrace',
    desc: 'Tears of joy and ancestral pride captured without intrusion. Quiet long-focal documentations that turn split seconds into multi-generational memories.',
    metaLeft: 'RAMBAGH MANDAP • CEREMONY',
    metaRight: 'FAMILY HEIRLOOM',
  },
  {
    id: 'arjun-kiara',
    layout: 'split',
    span: '12',
    aspect: '16/10',
    categories: 'pre-weddings engagements',
    youtubeId: '',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyMlQ6QdfKnj8mGvDTBt54in92xh4bBcpAZy2_wEUMh7m8vgxMFTC0T-wo6jvGD4A080I20d3RWRVdY_7d9-eLLgR1uleFQGN1PBsqmBLdJb7EdJizqV894gDHDHy_c1QBdcgvf8mHRkQ5yzyUiaplKNMhpH0KpG2VMO2g3SFfDVl7XGujlZwBxJ-ugZ8oBYptBcdRW7G2NX8D78HDFkGiMBpWBKHHcU-x9OnU9FrHG1UoL0crutg9WQ',
    eyebrow: 'EDITORIAL PRE-WEDDING ARCHIVE',
    note: 'FINE ART EXHIBITION',
    tags: [],
    title: 'Arjun & Kiara — Lake Pichola Twilight Glow',
    desc: "Conducted at Jagmandir Island at sunset. The couple was styled in bespoke velvet smoking jackets and champagne couture chiffon, mirrored by the tranquil ripples of Udaipur's golden waters.",
    metaLeft: 'UDAIPUR, INDIA',
    metaRight: 'GOLDEN HOUR SESSION',
  },
];
