// Services shipped with the site — one list powering both the home page
// "What we create" grid and the Services page collections.
//
// title/desc/tag1/tag2/image drive the compact home grid. The page* fields are
// the longer Services-page treatment; each falls back to its short counterpart
// when blank, so a newly added service renders on both pages immediately.

export const SERVICES = [
  {
    id: 'wedding-films',
    title: 'WEDDING FILMS',
    desc: 'Feature-length and theatrical cut wedding narratives recorded with multi-camera cinema rigs and custom film sound design.',
    tag1: '4K MASTER',
    tag2: "DIRECTOR'S CUT",
    image: '/assets/service-wedding-films.jpg',
    collection: 'COLLECTION I',
    badge: 'FLAGSHIP FEATURE',
    badge2: '6K MASTER',
    pageTitle: 'HAUTE WEDDING FILMS',
    pageDesc: 'Narrative feature-length cinema constructed with theatrical gravitas. Multi-angle dual cinema camera setups, bespoke original composition licensing, and multi-track dialogue mastering that anchors your vows in acoustic immortality.',
    pageImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEYOMf4c9GitEZvHfWkMB3QznRtQvRAM1EN0VU0TeGLlBt6tOp0zgg3j-C3HUDUti-pteVYrrL0z1JIfFFyg7-U2Y6s8o_Jg5ycd5V2I68l6JSrYAT06u8G2o35ihJ6hh_2FjkpQHG8ABTTNGQ6zYCq3fFHMYWewwKaasPJs4BOfLv6QsvGXUoAJdfSkUwVUe8MKEGwbHX6Cv7rEXWPAfdCeWmsM2-KcjlAExgHbgao64mutzchWXpEQ',
    deliverablesLabel: 'DELIVERABLES ARCHIVE',
    deliverables: [
      '45–60 min Master Theatrical Feature Cut',
      '3–5 min Poetic Trailer (Festival Grade)',
      'Hard drive vault containing 4K HDR ProRes master',
    ],
    optics: 'Sony FX6 / FX3 Dual Cine Bodies • Cooke & Atlas Anamorphic Prime Lenses • Lectrosonics Dual RF Audio Systems',
    cta: 'COMMISSION WEDDING FILM',
    note: 'LIMITED DATES',
  },
  {
    id: 'wedding-photography',
    title: 'WEDDING PHOTOGRAPHY',
    desc: 'High-fashion editorial stills and authentic documentary photojournalism that captures raw, unprompted elegance.',
    tag1: 'FINE ART PRINTS',
    tag2: 'HIGH RES ARCHIVE',
    image: '/assets/service-wedding-photography.jpg',
    collection: 'COLLECTION II',
    badge: 'FINE ART STILLS',
    pageTitle: 'EDITORIAL PHOTOGRAPHY',
    pageDesc: 'High-fashion editorial stills merged seamlessly with unscripted documentary photojournalism. Capturing stolen glances, sartorial silhouettes, and the palpable tension of high-magnitude emotion.',
    pageImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjxlSL-iizywlSZBCQCW4PMGDaMUxAK3xOKUw2d7H4l7YmRiNl44d2TUmVQpq86j70qdJLZKO6kT7VVp1La0JrP34WCYgarcGlTo5Mmhn3dfAUlQycW9Xy6pD9RSHKULj_-bxY5xkOV_pQ6eoHEPsKJHeUZC4d-nN717hmMYKabXcVw1HwB2-ptlcxjo8Sj29zryGMCvhpbyuY8nhYb0MpP-M-q3S2IVezcSOziISkslqN_iuiSSG-vg',
    deliverablesLabel: 'DELIVERABLES',
    deliverables: [
      '350+ Bespoke Hand-Graded High-Resolution Stills',
      'Hand-bound Heirloom Archival Linen Album (Made in Florence)',
      'Private Encrypted Proofing Gallery',
    ],
    optics: 'Leica SL2 & Sony A1 • Noctilux 50mm f/0.95 & Master G Primes',
    cta: 'EXPLORE STILL PORTFOLIO',
  },
  {
    id: 'pre-wedding-films',
    title: 'PRE-WEDDING FILMS',
    desc: "Conceptual short cinematic vignettes built around the couple's intimate genesis story, curated styling, and destination backdrops.",
    tag1: 'STORYBOARDED',
    tag2: 'DESTINATION',
    image: '/assets/service-prewedding-films.jpg',
    collection: 'COLLECTION III',
    badge: 'DESTINATION PROLOGUE',
    pageTitle: 'PRE-WEDDING FILMS',
    pageDesc: 'Conceptual short cinematic vignettes set against extraordinary global backdrops—from Venetian canals to Lake Como and Rajasthani desert fortresses. Comprehensive wardrobe moodboards and narrative storyboarding included.',
    pageImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB3N_C5bMyMAZepo-cML5nk0Nmnsg8ugaKXRMdMhCA4O2QV0QMZvhufXKIBXOBvnVUz_vHboQ_hoxAdrHPnl-wCljcz2VAitLmWh6EIqewcuhxTJp5bCS7l_wQpkAn4GIzBLpd-P5YjBxFF0VgiJLFGIJcBS8dGijbMMua55FHsJI84w0Noj9N6autEo4KatR9jIPU1C2jupjZqxIyCdiXYW5yPa7cxhkD6CQn3aEea7d1_xH9jUTv_fw',
    deliverablesLabel: 'DELIVERABLES',
    deliverables: [
      '3–5 min Theatrical Narrative Vignette',
      '4 High-End 9:16 Vertical Cuts for Mobile Devices',
      'Concept Moodboard & Styling Direction Session',
    ],
    optics: 'Steadicam Rigging • Zeiss Supreme Primes • Super 8mm Analog Texture Pass',
    cta: 'PLAN DESTINATION PROLOGUE',
  },
  {
    id: 'engagement-stories',
    title: 'ENGAGEMENT STORIES',
    desc: 'Intimate portraits and audio documentary tracking the immediate chapter of commitment, family bonding, and candid exchange.',
    tag1: 'INTIMATE SOIRÉE',
    tag2: 'AUDIO VOWS',
    image: '/assets/service-engagement-stories.jpg',
    collection: 'COLLECTION IV',
    badge: 'INTIMATE PORTRAITURE',
    pageTitle: 'ENGAGEMENT STORIES',
    pageDesc: 'Unvarnished micro-documentaries capturing the immediate aftermath of the proposal. Audio recordings of personal reflections paired with quiet, cinematic portraiture.',
    pageImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBLskSYFHb6AXTy1QJ7z-mONANdCnucrf71I-zZuYWnQqSQaQMeNXQ4a_qTovL2Cy6wh7ioe5GCCvfT1JGFyQD4Ba3W_BkK1vlY21O1qli8LyBg5T_H7rH3T9N9MkmCNqXwdspQ7j8nRsO_yUIJNT8QqowtofTQx2W1WekCjUvlChdh0xXB0gS65y0_JUiA7oqeC2iYbcg9cX9rgqNxdDty-oGHLtRTy1CMBLPd9AIL717eu2eIcP1osQ',
    deliverablesLabel: 'OUTPUT',
    deliverables: [
      '2-Day Quick-Edits for social announcement',
      'Complete 8-10 min archival audio-visual documentary chronicle.',
    ],
    optics: '',
    cta: 'INQUIRE ENGAGEMENT',
  },
  {
    id: 'cinematic-reels',
    title: 'CINEMATIC REELS',
    desc: 'High-velocity vertical teasers engineered for digital showcase without losing cinematic grade color science and motion blur.',
    tag1: '9:16 VERTICAL',
    tag2: 'FAST-TURNAROUND',
    image: '/assets/service-cinematic-reels.jpg',
    collection: 'COLLECTION V',
    badge: 'RAPID EDITORIAL',
    pageTitle: 'REELS & SAME-DAY EDITS',
    pageDesc: 'On-site editorial editing suites operating in real-time. Unmatched velocity without sacrificing our signature tone curves, film grain emulations, or acoustic punch.',
    pageImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGu6ZXeVQHoSt-qAA_s-YtEY5kkK4jsHX3U2EyhVw_SnyHyOBytNFvkir0gIjkC1VKi591JjqoeJnRybVP576HdzgYCZ-LIxDjmNuDuX17OlruAT-s3QtE0sBtsF2BgBa9kQujGzKvj2VCjY9CsxvX5iKTcO2Mwr1wqhvpOXQWh37_9goWahG4KR470izfI0J2Cp8JX9Mr008Pj1aDrUJBpvisfLmxmNFwWMnIiEb3gL5sdvcisLc3dw',
    deliverablesLabel: 'OUTPUT',
    deliverables: [
      '48-Hour delivery guarantee on high-velocity 9:16 vertical reels',
      'Master Reception Cut screened same evening for guests.',
    ],
    optics: '',
    cta: 'SAME-DAY AVAILABILITY',
  },
  {
    id: 'drone-coverage',
    title: 'DRONE COVERAGE',
    desc: 'Certified aerial pilotage capturing sprawling palace architecture, mountain landscapes, and vast procession scales from above.',
    tag1: 'PRO-RES CINEMA',
    tag2: 'ARCHITECTURAL SCALE',
    image: '/assets/service-drone-coverage.jpg',
    collection: 'COLLECTION VI',
    badge: 'CERTIFIED AERIAL',
    pageTitle: 'ARCHITECTURAL DRONE',
    pageDesc: 'Certified DGCA licensed aerial operators maneuvering cinema-grade aerial platforms. Capturing majestic palace scale, sweeping mountain valleys, and monumental symmetry.',
    pageImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSlsPntPXeKKrC_YIXx3xdp7vOKkYY8lkrsWNPTOAUPaveBSM_QUa74NFdcvm0DRrPfxDKOiXKleoICnW_z2Fhv5gqPJRjmvOoKnQE952vw20rAMjBZS0RzM7gGCzBIYuA3jNt4M2vkK6sf1Y_jmJx8_gbhmMBZuQ1UHK4F8VgfC_TG3OwWYyi-QCFKfZSErxp_Etv8w4K4RYJTFsn85Evqf4pZ9S_TEUADQs9IoI9_G6T-vh5lm8Kjg',
    deliverablesLabel: 'OUTPUT',
    deliverables: [
      '5.1K Apple ProRes 422 HQ aerial plates',
      'High-angle establishing master compositions for feature cinema inclusion.',
    ],
    optics: '',
    cta: 'EXPLORE FLIGHT PROTOCOLS',
  },
];
