// Home page content shipped with the site. The admin panel saves overrides to
// slicex_content under the "home" key; the page merges them in at runtime.
// Service cards and packages live under their own keys and are edited there.

export const HOME = {
  hero: {
    videoId: '96ztpzXcrlQ',
    badgeLeft: 'ARCHIVE EST. 2019 / WORLDWIDE COMMISSIONS',
    badgeRight: '35MM • ARRI RAW • ANAMORPHIC AQUA EDITION',
    eyebrow: 'FINE ART CINEMATOGRAPHY',
    titleA: 'YOUR STORY.',
    titleB: 'OUR FRAME.',
    subtitle: 'A creative production house crafting visual experiences across films, advertising, weddings, podcasts, brands, events and documentaries.',
    quote: 'From concept to final frame,\nwe turn ideas into visual stories.',
    quoteBrand: 'SliceX Films',
    quoteTag: 'Where Stories Become Cinema.',
    btn1: 'VIEW OUR WORK',
    btn2: 'BOOK YOUR DATE',
    strip: 'SLICEX FILMS • CAPTURE • CREATE • INSPIRE',
    scrollLabel: 'SCROLL TO EXPLORE',
  },
  about: {
    index: '01 / ABOUT SLICEX',
    titleA: 'WE DON’T JUST CAPTURE MOMENTS.',
    titleB: 'WE CREATE STORIES.',
    statement: 'DIRECTOR’S STATEMENT • CUT 2025',
    quote: '“At SliceX Films, we don’t just capture couples—we cast them. Whether it’s a shy smile or an inside joke, we see every couple as the lead characters in their own story. It’s never about how they look, dress, or pose. To us, every couple is a hero and heroine—worthy of their own movie.”',
    body: 'SliceX Films is about turning ordinary love stories into timeless visuals. Because in our lens, everyone deserves to feel like they’re on the big screen. We combine the pacing of indie cinema with the grandeur of high-fashion print editorial.',
    cta: 'EXPLORE OUR CRAFT',
    locations: ['BHUBANESWAR', 'UDAIPUR', 'GLOBAL'],
  },
  filmStrip: {
    eyebrow: 'ARCHIVAL NEGATIVE ROLL // KODAK VISION3 & PORTRA 400 EMULSION',
    title: '35MM CONTINUOUS FILM STRIP',
    hint: 'DRAG TO EXPLORE · CLICK TO PLAY',
    hintRight: 'DIRECT CAMERA RAW ARCHIVE',
    footLeft: 'CANON RF 50MM F/1.2L • LEICA M11 ARCHIVE • ARRI ALEXA MINI LF EMULSION',
    footRight: 'DYNAMIC CMS CURATION ENABLED',
    footLink: 'INQUIRE NEGATIVES ACCESS →',
    items: [
      { id: 'YomPpYhVIws', title: 'Niharika & Chandan', tag: 'Pre-Wedding', stock: 'KODAK 5219' },
      { id: 'EUB8I5jshbI', title: 'Swarup & Soumya', tag: 'Wedding Film', stock: 'SAFETY FILM' },
      { id: '8NngCj7b_uA', title: 'Alisha Dash', tag: 'Wedding Film', stock: 'EASTMAN 400' },
      { id: 'ELOK2RXqbuc', title: 'Bikash & Akanksha', tag: 'Safar · Part 2', stock: 'PORTRA 400' },
      { id: 'k5D1tdXx4rE', title: 'Sibhani as Apsara', tag: 'Concept Film', stock: 'KODAK VISION3' },
      { id: 'ywVU5sfR5Ao', title: 'Piyush & Dipti', tag: 'Wedding Film', stock: 'VOGUE SPOSA' },
      { id: 'NI94Lry-Llo', title: 'Pratyush & Mitali', tag: 'Wedding Film', stock: 'CINESTILL 800T' },
      { id: 'LbZdGXwFpg4', title: 'Pratyush & Mitali', tag: 'Pre-Wedding Teaser', stock: 'KODAK 500T' },
      { id: '71sezFct5YQ', title: 'Sulagna', tag: "A Bride's Perspective", stock: 'FUJI ETERNA' },
    ],
  },
  services: {
    index: '02 / SERVICES',
    title: 'WHAT WE CREATE',
    blurb: 'Curated cinematic modalities executed on cinema prime lenses and calibrated archival grade finishing.',
  },
  featured: {
    index: '03 / EXHIBITION',
    title: 'FEATURED WORK',
    items: [
      { id: 'BApJaloacXg', label: '01 / FEATURED FILM', title: 'SANJEEB & ASHA — FULL WEDDING FILM', desc: 'A full three-act wedding film — every ritual, toast, and unscripted tear.', cta: 'VIEW FILM' },
      { id: '8NngCj7b_uA', label: '02 / WEDDING FILM', title: 'ALISHA DASH', desc: 'Warm, candid storytelling — the day exactly as it unfolded.', cta: 'WATCH FILM →' },
      { id: 'r4KTSRpp17s', label: '03 / PRE-WEDDING', title: 'DILLU & DIKSHYA', desc: 'A cinematic pre-wedding love story shot on location.', cta: 'WATCH TEASER →' },
      { id: '6GrJci58sFQ', label: '04 / ENGAGEMENT', title: 'ABHISHEK & NEHA', desc: 'An intimate engagement celebration captured with a filmmaker’s eye.', cta: 'WATCH FILM →' },
    ],
  },
  screening: {
    index: '04 / THE SCREENING ROOM',
    title: 'CINEMATIC MASTERPIECES',
    blurb: 'Experience our bespoke 4K theatrical edits calibrated for acoustic precision and high-dynamic-range color artistry.',
    watchLabel: 'WATCH ON YOUTUBE',
    nowShowingLabel: 'NOW SHOWING',
    // Each card is a selector: tapping one swaps the film shown in the player
    // above. Descriptions are left blank to be written in the admin.
    featureVideos: [
      { id: '96ztpzXcrlQ', category: 'FILM 01 • WEDDING FILM', title: 'ANANYA & SWAPNIL', desc: '', cta: 'VIEW FILM' },
      { id: '6GrJci58sFQ', category: 'FILM 02 • ENGAGEMENT', title: 'ABHISHEK & NEHA', desc: '', cta: 'VIEW FILM' },
      { id: '1VxeldJy_4s', category: 'FILM 03 • WEDDING FILM', title: 'SAFAR · PART 3 — AKANKSHA & BIKASH', desc: '', cta: 'VIEW FILM' },
      { id: 'YomPpYhVIws', category: 'FILM 04 • PRE-WEDDING', title: 'NIHARIKA & CHANDAN', desc: '', cta: 'VIEW FILM' },
    ],
  },
  creed: {
    eyebrow: 'THE CORE CREED',
    line1: 'EVERY COUPLE',
    line2: 'HAS A STORY.',
    line3: 'WE MAKE SURE',
    line4: 'IT FEELS LIKE',
    line5: 'A MOVIE.',
    foot: 'SLICEX FILMS PRODUCTION HOUSE • FINE CINEMATOGRAPHY',
  },
  method: {
    index: '05 / THE METHOD',
    title: 'HOW WE ARCHIVE YOUR DAY',
    blurb: 'From the initial script session to the hand-delivered 4K master archive box.',
    steps: [
      { num: '01', badge: 'DISCOVERY', title: 'MEET', image: '/assets/step-meet.jpg', desc: 'We meet over espresso or video link to understand your quirks, your tempo, and the personal dynamics you care about.' },
      { num: '02', badge: 'DESIGN', title: 'PLAN', image: '/assets/step-plan.jpg', desc: 'Architecting camera angles, light timing, mood boards, wardrobe harmonies, and timeline synchronization.' },
      { num: '03', badge: 'CINEMA', title: 'CAPTURE', image: '/assets/step-capture.jpg', desc: 'Discreet, non-invasive cinema coverage. We observe raw authenticity without intrusive studio orchestrations.' },
      { num: '04', badge: 'POST', title: 'CREATE', image: '/assets/step-create.jpg', desc: 'Surgical editorial pacing, analog-feel color grading, bespoke film score licensing, and sound engineering.' },
      { num: '05', badge: 'ARCHIVE', title: 'DELIVER', image: '/assets/step-deliver.jpg', desc: 'Secure private streaming vault plus a luxury keepsake archive drive crafted for generations of viewing.' },
    ],
  },
  commission: {
    index: '06 / INVESTMENT COMMISSIONS',
    title: 'CURATED OFFERINGS',
    blurb: 'Transparent commission structures tailored for intimate gatherings to grand royal multi-day destination events.',
    formEyebrow: 'CALENDAR INQUIRY',
    formTitle: 'SECURE YOUR DATES',
    formBlurb: 'We accept a strictly limited number of commissions per season to ensure unwavering director involvement.',
    formNote: 'DATA CONFIDENTIALITY GUARANTEED',
    submitLabel: 'SUBMIT INQUIRY',
    successMessage: 'Inquiry received. The SliceX directorial team will reach out within 24 hours.',
  },
};
